spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081/
            predicates:
              - path= /customers/**
          - id: r2
            uri: http://localhost:8082/
            predicates:
              - path= /accounts/**
    discovery:
      enabled: false
server:
  port: 8088